language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - 2.7
  - 3.6
  - 3.7
before_install:
install:
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls

notifications:
  email:
    - rene@jochums.at
